# Generated by Django 3.0.3 on 2020-03-02 12:16

import Agent.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agentuploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Agent.models.user_directory_path)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=200)),
                ('file_name1', models.CharField(max_length=200)),
                ('filetype', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
