# Generated by Django 3.0.3 on 2020-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuploads',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='agentuploads',
            name='file_name1',
        ),
        migrations.RemoveField(
            model_name='agentuploads',
            name='filetype',
        ),
        migrations.AddField(
            model_name='agentuploads',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentuploads',
            name='property_Description',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentuploads',
            name='property_Location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentuploads',
            name='property_Name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentuploads',
            name='property_Type',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
