# Generated by Django 3.0.3 on 2020-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_auto_20200316_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentuploads',
            name='property_Description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentuploads',
            name='property_Type',
            field=models.CharField(max_length=100),
        ),
    ]
