# Generated by Django 3.0.3 on 2020-03-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_auto_20200318_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuploads',
            name='property_Address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
