# Generated by Django 3.0.3 on 2020-03-24 12:09

import Agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0009_agentuploads_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuploads',
            name='file2',
            field=models.FileField(default=1, upload_to=Agent.models.user_directory_path),
            preserve_default=False,
        ),
    ]
