# Generated by Django 3.0.3 on 2020-03-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
