# Generated by Django 3.0.3 on 2020-03-20 01:56

from django.db import migrations, models
import moborise.models


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0004_profilpicx'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='img',
            field=models.ImageField(default=1, upload_to=moborise.models.user_directory_path),
            preserve_default=False,
        ),
    ]
