# Generated by Django 3.0.3 on 2020-03-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0006_profilpicx_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilpicx',
            name='author',
        ),
    ]
