# Generated by Django 3.0.3 on 2020-03-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0009_auto_20200320_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='author',
        ),
    ]
