# Generated by Django 3.0.3 on 2020-03-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0010_remove_usertype_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilpicx',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='img',
            field=models.FileField(upload_to='gallery/profile/'),
        ),
    ]
