# Generated by Django 3.0.3 on 2020-03-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
