# Generated by Django 3.0.3 on 2020-03-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0013_auto_20200323_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to',
        ),
    ]
